server:
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    name: seckill
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.97.125.200
    port: 6379
    database: 10
    jedis:
      pool:
        max-active: 50
        min-idle: 20
logging:
  level:
    com.aiolos.seckill.dao : debug

mq:
  nameserver:
    addr: 47.97.125.200:9876
  topicname: stock
